/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Framework.Modules.Menu.View;

/**
 *
 * 
 */
public class choose_frame extends javax.swing.JFrame {

    /**
     * Creates new form choose_frame
     */
    public choose_frame() {
        initComponents();        
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_adm = new javax.swing.JButton();
        btn_client = new javax.swing.JButton();
        btn_user_reg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_adm.setText("Admin");

        btn_client.setText("Client");

        btn_user_reg.setText("Usr_Reg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btn_adm)
                .addGap(23, 23, 23)
                .addComponent(btn_client)
                .addGap(24, 24, 24)
                .addComponent(btn_user_reg)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adm)
                    .addComponent(btn_client)
                    .addComponent(btn_user_reg))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_adm;
    private javax.swing.JButton btn_client;
    private javax.swing.JButton btn_user_reg;
    // End of variables declaration//GEN-END:variables
}