/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Framework.Modules.Menu.View;

import Framework.Modules.Menu.Model.Clases.Class_language;

/**
 *
 * @author usuario
 */
public class config_frame extends javax.swing.JFrame {

    /**
     * Creates new form config_frame
     */
    public config_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.ButtonGroup();
        theme = new javax.swing.ButtonGroup();
        currency = new javax.swing.ButtonGroup();
        language = new javax.swing.ButtonGroup();
        decimal = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        choose_format = new javax.swing.JTabbedPane();
        paneldate = new javax.swing.JPanel();
        eti_format_date = new javax.swing.JTextField();
        date_ddMMyyyy_barra = new javax.swing.JRadioButton();
        date_yyyyMMdd_barra = new javax.swing.JRadioButton();
        date_ddMMyyyy_guion = new javax.swing.JRadioButton();
        date_yyyyMMdd_guion = new javax.swing.JRadioButton();
        btn_accept_date = new javax.swing.JButton();
        btn_cancel_date = new javax.swing.JButton();
        paneltheme = new javax.swing.JPanel();
        eti_format_theme = new javax.swing.JTextField();
        theme_metal = new javax.swing.JRadioButton();
        theme_windows = new javax.swing.JRadioButton();
        theme_motif = new javax.swing.JRadioButton();
        theme_nimbus = new javax.swing.JRadioButton();
        btn_accept_theme = new javax.swing.JButton();
        btn_cancel_theme = new javax.swing.JButton();
        panelcurrency = new javax.swing.JPanel();
        currency_euro = new javax.swing.JRadioButton();
        eti_format_currency = new javax.swing.JTextField();
        currency_dolar = new javax.swing.JRadioButton();
        currency_libra = new javax.swing.JRadioButton();
        btn_accept_currency = new javax.swing.JButton();
        btn_cancel_currency = new javax.swing.JButton();
        panellanguage = new javax.swing.JPanel();
        eti_format_language = new javax.swing.JTextField();
        language_valencian = new javax.swing.JRadioButton();
        language_spanish = new javax.swing.JRadioButton();
        language_english = new javax.swing.JRadioButton();
        btn_accept_language = new javax.swing.JButton();
        btn_cancel_language = new javax.swing.JButton();
        paneldecimal = new javax.swing.JPanel();
        eti_format_decimal = new javax.swing.JTextField();
        decimal_1decimal = new javax.swing.JRadioButton();
        decimal_2decimal = new javax.swing.JRadioButton();
        decimal_3decimal = new javax.swing.JRadioButton();
        btn_accept_decimal = new javax.swing.JButton();
        btn_cancel_decimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eti_format_date.setEditable(false);
        eti_format_date.setText(Class_language.getInstance().getProperty("date2"));

        date.add(date_ddMMyyyy_barra);
        date_ddMMyyyy_barra.setText("dd/MM/yyyy");

        date.add(date_yyyyMMdd_barra);
        date_yyyyMMdd_barra.setText("yyyy/MM/dd");

        date.add(date_ddMMyyyy_guion);
        date_ddMMyyyy_guion.setText("dd-MM-yyyy");

        date.add(date_yyyyMMdd_guion);
        date_yyyyMMdd_guion.setText("yyyy-MM-dd");

        btn_accept_date.setText(Class_language.getInstance().getProperty("accept"));

        btn_cancel_date.setText(Class_language.getInstance().getProperty("cancel"));

        javax.swing.GroupLayout paneldateLayout = new javax.swing.GroupLayout(paneldate);
        paneldate.setLayout(paneldateLayout);
        paneldateLayout.setHorizontalGroup(
            paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eti_format_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneldateLayout.createSequentialGroup()
                        .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_accept_date)
                            .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date_ddMMyyyy_barra)
                                .addComponent(date_ddMMyyyy_guion)))
                        .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneldateLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date_yyyyMMdd_guion)
                                    .addComponent(date_yyyyMMdd_barra)))
                            .addGroup(paneldateLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btn_cancel_date)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        paneldateLayout.setVerticalGroup(
            paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eti_format_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_ddMMyyyy_barra)
                    .addComponent(date_yyyyMMdd_barra))
                .addGap(31, 31, 31)
                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_ddMMyyyy_guion)
                    .addComponent(date_yyyyMMdd_guion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(paneldateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept_date)
                    .addComponent(btn_cancel_date))
                .addGap(54, 54, 54))
        );

        choose_format.addTab(Class_language.getInstance().getProperty("Date"), paneldate);

        eti_format_theme.setEditable(false);
        eti_format_theme.setText(Class_language.getInstance().getProperty("theme2"));

        theme.add(theme_metal);
        theme_metal.setText("Metal");

        theme.add(theme_windows);
        theme_windows.setText("Windows");

        theme.add(theme_motif);
        theme_motif.setText("Motif");

        theme.add(theme_nimbus);
        theme_nimbus.setText("Nimbus");

        btn_accept_theme.setText(Class_language.getInstance().getProperty("accept"));

        btn_cancel_theme.setText(Class_language.getInstance().getProperty("cancel"));

        javax.swing.GroupLayout panelthemeLayout = new javax.swing.GroupLayout(paneltheme);
        paneltheme.setLayout(panelthemeLayout);
        panelthemeLayout.setHorizontalGroup(
            panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelthemeLayout.createSequentialGroup()
                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelthemeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eti_format_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelthemeLayout.createSequentialGroup()
                                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(theme_metal)
                                    .addComponent(theme_motif))
                                .addGap(42, 42, 42)
                                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(theme_nimbus)
                                    .addComponent(theme_windows)))))
                    .addGroup(panelthemeLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_accept_theme)
                        .addGap(30, 30, 30)
                        .addComponent(btn_cancel_theme)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        panelthemeLayout.setVerticalGroup(
            panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelthemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eti_format_theme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theme_metal)
                    .addComponent(theme_windows))
                .addGap(34, 34, 34)
                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(theme_motif)
                    .addComponent(theme_nimbus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panelthemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept_theme)
                    .addComponent(btn_cancel_theme))
                .addGap(56, 56, 56))
        );

        choose_format.addTab(Class_language.getInstance().getProperty("Theme"), paneltheme);

        currency.add(currency_euro);
        currency_euro.setText("EURO");

        eti_format_currency.setEditable(false);
        eti_format_currency.setText(Class_language.getInstance().getProperty("currency2"));

        currency.add(currency_dolar);
        currency_dolar.setText("DOLAR");

        currency.add(currency_libra);
        currency_libra.setText("LIBRA");

        btn_accept_currency.setText(Class_language.getInstance().getProperty("accept"));

        btn_cancel_currency.setText(Class_language.getInstance().getProperty("cancel"));

        javax.swing.GroupLayout panelcurrencyLayout = new javax.swing.GroupLayout(panelcurrency);
        panelcurrency.setLayout(panelcurrencyLayout);
        panelcurrencyLayout.setHorizontalGroup(
            panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcurrencyLayout.createSequentialGroup()
                .addGroup(panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcurrencyLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(eti_format_currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelcurrencyLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(currency_euro)
                        .addGap(41, 41, 41)
                        .addComponent(currency_dolar)
                        .addGap(41, 41, 41)
                        .addComponent(currency_libra))
                    .addGroup(panelcurrencyLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_accept_currency)
                        .addGap(39, 39, 39)
                        .addComponent(btn_cancel_currency)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelcurrencyLayout.setVerticalGroup(
            panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcurrencyLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(eti_format_currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currency_euro)
                    .addComponent(currency_dolar)
                    .addComponent(currency_libra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(panelcurrencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept_currency)
                    .addComponent(btn_cancel_currency))
                .addGap(59, 59, 59))
        );

        choose_format.addTab(Class_language.getInstance().getProperty("Currency"), panelcurrency);

        eti_format_language.setEditable(false);
        eti_format_language.setText(Class_language.getInstance().getProperty("language2"));

        language.add(language_valencian);
        language_valencian.setText("VALENCIAN");

        language.add(language_spanish);
        language_spanish.setText("SPANISH");

        language.add(language_english);
        language_english.setText("ENGLISH");

        btn_accept_language.setText(Class_language.getInstance().getProperty("accept"));

        btn_cancel_language.setText(Class_language.getInstance().getProperty("cancel"));

        javax.swing.GroupLayout panellanguageLayout = new javax.swing.GroupLayout(panellanguage);
        panellanguage.setLayout(panellanguageLayout);
        panellanguageLayout.setHorizontalGroup(
            panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellanguageLayout.createSequentialGroup()
                .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(eti_format_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(language_valencian)
                        .addGap(26, 26, 26)
                        .addComponent(language_spanish)
                        .addGap(18, 18, 18)
                        .addComponent(language_english))
                    .addGroup(panellanguageLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_accept_language)
                        .addGap(43, 43, 43)
                        .addComponent(btn_cancel_language)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panellanguageLayout.setVerticalGroup(
            panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellanguageLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(eti_format_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(language_valencian)
                    .addComponent(language_spanish)
                    .addComponent(language_english))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panellanguageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept_language)
                    .addComponent(btn_cancel_language))
                .addGap(57, 57, 57))
        );

        choose_format.addTab(Class_language.getInstance().getProperty("Language"), panellanguage);

        eti_format_decimal.setEditable(false);
        eti_format_decimal.setText(Class_language.getInstance().getProperty("decimal2"));

        decimal.add(decimal_1decimal);
        decimal_1decimal.setText("1 DECIMAL");

        decimal.add(decimal_2decimal);
        decimal_2decimal.setText("2 DECIMAL");

        decimal.add(decimal_3decimal);
        decimal_3decimal.setText("3 DECIMAL");

        btn_accept_decimal.setText(Class_language.getInstance().getProperty("accept"));

        btn_cancel_decimal.setText(Class_language.getInstance().getProperty("cancel"));

        javax.swing.GroupLayout paneldecimalLayout = new javax.swing.GroupLayout(paneldecimal);
        paneldecimal.setLayout(paneldecimalLayout);
        paneldecimalLayout.setHorizontalGroup(
            paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldecimalLayout.createSequentialGroup()
                .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldecimalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneldecimalLayout.createSequentialGroup()
                                .addComponent(decimal_1decimal)
                                .addGap(27, 27, 27)
                                .addComponent(decimal_2decimal)
                                .addGap(29, 29, 29)
                                .addComponent(decimal_3decimal))
                            .addComponent(eti_format_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneldecimalLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btn_accept_decimal)
                        .addGap(36, 36, 36)
                        .addComponent(btn_cancel_decimal)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        paneldecimalLayout.setVerticalGroup(
            paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldecimalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(eti_format_decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimal_1decimal)
                    .addComponent(decimal_2decimal)
                    .addComponent(decimal_3decimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(paneldecimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accept_decimal)
                    .addComponent(btn_cancel_decimal))
                .addGap(54, 54, 54))
        );

        choose_format.addTab(Class_language.getInstance().getProperty("Decimal"), paneldecimal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choose_format)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(choose_format)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_accept_currency;
    public static javax.swing.JButton btn_accept_date;
    public static javax.swing.JButton btn_accept_decimal;
    public static javax.swing.JButton btn_accept_language;
    public static javax.swing.JButton btn_accept_theme;
    public static javax.swing.JButton btn_cancel_currency;
    public static javax.swing.JButton btn_cancel_date;
    public static javax.swing.JButton btn_cancel_decimal;
    public static javax.swing.JButton btn_cancel_language;
    public static javax.swing.JButton btn_cancel_theme;
    public static javax.swing.JTabbedPane choose_format;
    public static javax.swing.ButtonGroup currency;
    public static javax.swing.JRadioButton currency_dolar;
    public static javax.swing.JRadioButton currency_euro;
    public static javax.swing.JRadioButton currency_libra;
    public static javax.swing.ButtonGroup date;
    public static javax.swing.JRadioButton date_ddMMyyyy_barra;
    public static javax.swing.JRadioButton date_ddMMyyyy_guion;
    public static javax.swing.JRadioButton date_yyyyMMdd_barra;
    public static javax.swing.JRadioButton date_yyyyMMdd_guion;
    public static javax.swing.ButtonGroup decimal;
    public static javax.swing.JRadioButton decimal_1decimal;
    public static javax.swing.JRadioButton decimal_2decimal;
    public static javax.swing.JRadioButton decimal_3decimal;
    private javax.swing.JTextField eti_format_currency;
    private javax.swing.JTextField eti_format_date;
    private javax.swing.JTextField eti_format_decimal;
    private javax.swing.JTextField eti_format_language;
    private javax.swing.JTextField eti_format_theme;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.ButtonGroup language;
    public static javax.swing.JRadioButton language_english;
    public static javax.swing.JRadioButton language_spanish;
    public static javax.swing.JRadioButton language_valencian;
    private javax.swing.JPanel panelcurrency;
    public static javax.swing.JPanel paneldate;
    private javax.swing.JPanel paneldecimal;
    private javax.swing.JPanel panellanguage;
    private javax.swing.JPanel paneltheme;
    public static javax.swing.ButtonGroup theme;
    public static javax.swing.JRadioButton theme_metal;
    public static javax.swing.JRadioButton theme_motif;
    public static javax.swing.JRadioButton theme_nimbus;
    public static javax.swing.JRadioButton theme_windows;
    // End of variables declaration//GEN-END:variables
}
