/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Framework.Modules.Menu.View;

import Framework.Modules.Login.Controller.Controller_login;
import Framework.Modules.Login.View.login_frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author usuario
 */
public class load_frame extends javax.swing.JFrame {
    private Timer timer;
        int cont=-1,i=0;
        public final static int ONE_SECOND = 8;
    /**
     * Creates new form load_menu
     */
    public load_frame() {
        //cont =-1;
        initComponents();
        timer = new Timer(ONE_SECOND, new TimerListener());
        timer.start();
        this.setTitle("Loading");
	this.setLocationRelativeTo(null);
	//this.setSize(1025,625);//ancho x alto
	this.setResizable(false);
	//Image icono=Toolkit.getDefaultToolkit().getImage("p1.jpg");
	//this.setIconImage(icono);
	this.setExtendedState(JFrame.MAXIMIZED_BOTH); //la aplicación se abre maximizada
    }
    class TimerListener implements ActionListener {
        public void actionPerformed(ActionEvent evt) {
            cont++;
            //eti_load.setValue(cont);
            if(cont==200){
                timer.stop();
                dispose();

                if (i==0){
                    i++;
                    new Controller_login(new login_frame()).began();    
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eti_load = new javax.swing.JLabel();
        eti_escudo_load = new javax.swing.JLabel();
        eti_loading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eti_load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Framework/img/animated-loading-bar.gif"))); // NOI18N

        eti_escudo_load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Framework/img/Imagen-animada-Ciclismo-52.gif"))); // NOI18N

        eti_loading.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eti_loading.setText("LOADING...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(eti_loading))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(eti_load, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(eti_escudo_load)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(eti_escudo_load)
                .addGap(47, 47, 47)
                .addComponent(eti_load, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(eti_loading)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eti_escudo_load;
    private javax.swing.JLabel eti_load;
    private javax.swing.JLabel eti_loading;
    // End of variables declaration//GEN-END:variables
}
